### ISSUE TITLE
Permission denied error when trying to enable an engine

### ISSUE THREAD

**Issue by mssola** [codeclimate/codeclimate#14]
I've just installed this in a Linux machine. I'm trying to add a new engine by doing:

    $ codeclimate engines:enable rubocop

But I'm getting the following error:

    error: (Errno::EACCES) Permission denied @ rb_sysopen - /code/.codeclimate.yml

**Comment by mhlavac** [comment]
@mssola make sure to check to who the file belongs to. For me it was created with root:root, I changed it and also check permissions, make sure everyone can read it

**Comment by mssola** [comment]
Ah, now I see. I just had to give write permissions to everyone for this file. This happened because I created the `.codeclimate.yml` myself, and I did this before by executing `codeclimate init` I get exactly the same error:

    error: (Errno::EACCES) Permission denied @ rb_sysopen - /code/.codeclimate.yml

And moreover, something is telling me that this issue is related to #18

**Comment by pbrisbin** [comment]
Yes, I agree it's inconvenient and we're definitely working on ways to make this better -- unfortunately, it's a tricky problem.

For now the idea is that you use `codeclimate init` to create the file, and `codeclimate engines:x` to modify it. If those are true, you should not receive permissions errors because both operations run as the same user.

Until we implement a proper fix for the permissions of the codeclimate.yml file, I suggest the following:

- Set the file back to `root:root` and `644` permissions (or delete it and re-`init`)
- `engines:enable` should work now
- If you have to modify it by hand, please use `sudo`

Let me know if this works.

**Comment by mssola** [comment]
@pbrisbin I fixed it by given more permissions to everyone. Also note that by doing `codeclimate init` I get the same error as I mentioned before. So for me the fix is to create it manually and then set the proper permissions. If you are already working on this you can close this issue, since it seems that it's a duplicate of #18 ;)

**Comment by pbrisbin** [comment]
OK, I'm glad you're found a workaround. I'll close this since we are tracking (aspects of) this problem in other Issues and our Trello board.
