### ISSUE TITLE
Add a function to delete the temp folder.

### ISSUE THREAD

**Issue by envygeeks** [codeclimate/codeclimate#246]
At this current time you create a temp folder and then hold it as root, for systems that remain on for an extended period of time, this folder can grow with the number of projects tested, since you keep the folder as root I think it would be nice if you add a function to delete the files.

**Comment by pbrisbin** [comment]
Hi @envygeeks sorry for the late response here. You're right, claiming `/tmp/cc` was a poor decision we made early on and we'd like to correct it. Unfortunately, we just haven't been able to prioritize a solution just yet. Hopefully I'll be able to report back soon when we do.

**Comment by dblandin** [comment]
Hey @envygeeks, did #303 (now merged) address your concerns?

**Comment by envygeeks** [comment]
@dblandin I haven't check yet but I will be sure to check it out today.  However, as long as the /tmp/cc folder is gone then all complaints are address from this end so it's safe to close this!

**Comment by dblandin** [comment]
@envygeeks We're still using the host's `/tmp/cc` directory so that we can write out a config file used by the next engine container. The change made in #303 will ensure that the config file we create is removed.

No existing files within the host's `/tmp/cc` directory are accessed and we remove our own temporary file, but we do mount the `/tmp/cc` directory, create it it necessary, and leave it on the system.

You can see the volume mount within our [codeclimate-wrapper](https://github.com/codeclimate/codeclimate/blob/315f67791edb530378bc313eb59be04a5e94a2d1/codeclimate-wrapper#L57) script.

I'm guessing that we're using the specific `/tmp/cc` path to avoid volume mounting the entire `/tmp` directory. Bumping the volume mount up a level to `/tmp` would allow us to create a unique temp directory and completely remove it before exiting but would also expose more of the user's files/directories to the codeclimate container, which we'd like to avoid.

**Comment by dblandin** [comment]
Hey @envygeeks,

> However, as long as the /tmp/cc folder is gone then all complaints are address from this end so it's safe to close this!

As of [v0.22.1](https://github.com/codeclimate/codeclimate/releases/tag/v0.22.1), we now support a `CODECLIMATE_TMP` environment variable to specify a custom host directory for temporary files during Code Climate analyses.

Now that this enhancement is in place, I'm going to go ahead and close this issue. Thanks!
