### ISSUE TITLE
Installation issue - docker pull invalid command

### ISSUE THREAD

**Issue by chfast** [codeclimate/codeclimate#273]
```
Status: Downloaded newer image for codeclimate/codeclimate:latest
docker images | awk '/codeclimate\/codeclimate-/ { print $1 }' | xargs -n1 docker pull || true
docker: "pull" requires 1 argument.
See 'docker pull --help'.

Usage:	docker pull [OPTIONS] NAME[:TAG|@DIGEST]
```

Docker version 1.9.1, build a34a1d5

**Comment by pbrisbin** [comment]
Hi @chfast,

I agree that error output can be a bit confusing, but it shouldn't prevent the installation from continuing (the `|| true` basically means ignore this failure). It happens when you have no images on your system that need updating and `xargs` invokes `docker pull` without passing the `NAME` argument.

Can you check if, even with this output, the installation worked?

There's actually a convenient way to prevent this with an option to `xargs` but unfortunately it doesn't work on the BSD version (used by OS X).

**Comment by dblandin** [comment]
I'm going to go ahead and close this issue as it has been inactive for a while.

@chfast Let us know if you're still experiencing installation issues.
