### ISSUE TITLE
Rating paths, individual grades and overall GPA

### ISSUE THREAD

**Issue by prrrnd** [codeclimate/codeclimate#313]
Hi,

I am not getting any individual grade or overall GPA in the `analyze` output.
I'm pretty sure the ratings paths are correct.
I can't find help in the docs, so I thought I would ask here.

**Comment by wfleming** [comment]
Hi @prrrnd,

Right now grades are only calculated on https://codeclimate.com: the CLI doesn't support them yet. Sorry about that. Our docs could definitely be clearer about that, so I'll make a note to update that.

**Comment by prrrnd** [comment]
Thanks @wfleming - sounds like it's planned though, would be great!

**Comment by dblandin** [comment]
@wfleming I made a short note on our [ratings docs page](https://docs.codeclimate.com/v1.0/docs/ratings). Let me know if we need to update any READMEs as well.

**Comment by dblandin** [comment]
On second thought, I'm going to leave this issue open with its current "enhancement" label as a feature request.

**Comment by mikeLspohn** [comment]
Any word on the Overall GPA feature? The CLI is great, btw!

**Comment by wfleming** [comment]
GPA as an overall concept has been deprecated in our system, and we're moving towards a [a clearer rating system](http://blog.codeclimate.com/blog/2017/09/21/a-new-clearer-way-to-understand-code-quality/) that focuses on Maintainability & Test Coverage as overall concepts.

While the new ratings are still similar to "grades" in that they use a conventional A-F letter grade, the calculations that affect them are significantly different. Additionally, these rating calculations on codeclimate.com respond to real-time changes made by user actions like [changing the status of an issue](https://docs.codeclimate.com/docs/issues#section-issue-statuses), which isn't yet something the CLI can do.

This has been open a long time, and since these concepts are changing dramatically in Code Climate, I'm going to go ahead and close this for now. We can re-open or consider a different issue in the future when appropriate.
