### ISSUE TITLE
Include more details in JSON output

### ISSUE THREAD

**Issue by devth** [codeclimate/codeclimate#321]
Would be quite helpful if the JSON output from analysis included the line of code string in addition to position.

**Comment by wfleming** [comment]
The JSON formatter is mostly a pass-through of the raw issue data generated by individual engines, intended to be used for debugging or consumption by other software. [Our spec](https://github.com/codeclimate/spec/blob/master/SPEC.md#locations) allows engines to emit either line/column information or character offsets relative to the beginning of the file, whichever is more convenient.

If you're seeing JSON without line numbers it's probably because the engine chose to emit offsets instead. If you're seeing JSON without any `position` information at all, that would be a bug I'd want to look at, and would appreciate more info about what engine was running, what JSON was emitted, and the contents of the file being analyzed if possible.

**Comment by devth** [comment]
Thanks, but I meant the actual line of code, e.g.`puts :foo` in addition to the `position` data.

**Comment by wfleming** [comment]
Ah, sorry, I misunderstood.

When it comes to the actual content of the source file the issue relates to, we think that's more of a display concern than an data concern, and don't want engines to emit that source code directly into an issue for a variety of reasons. As one example, some engines report issues for things like "module too long", which would mean storing potentially hundreds of lines of source code in the JSON, which is excessive when the source file containing those lines will also be nearby & readable if that code needs to be shown for any reason.

This is pretty much what our own code does when it needs to, and if you're writing something making use of the JSON emitted by our CLI, I'd suggest the same thing: if you want to show the affected source, read it back out from the source file based on the information in the JSON.

If you don't mind, I'm going to go ahead & close this issue: we don't see this as a desirable part of the data schema for issues, and the JSON format is intended to be closely tied to schema, so this isn't something we're likely to change. But if you're building scripts or anything else on top of our CLI, I think you can implement what you need yourself.

**Comment by devth** [comment]
Cool, thanks for the explanation. Makes total sense. I've already done the work to read in the LoC from disk anyway :)
