### ISSUE TITLE
Support for markdownlint

### ISSUE THREAD

**Issue by devth** [codeclimate/codeclimate#322]
https://github.com/mivok/markdownlint

**Comment by wfleming** [comment]
Hi @devth,

I wasn't aware of this tool, so thanks for bringing it to our attention. I'm not sure when we might be able to get to doing this ourselves, but we're always happy to get OSS contributions for new engines if it's something you'd be interested in doing! Our [spec for engine behavior](https://github.com/codeclimate/spec) goes into more details about how engines are built & some reference implementations.

**Comment by devth** [comment]
@wfleming cool. I checked out the spec on building them but wasn't sure how to actually use a custom engine. It looks like `codeclimate engines:list` only includes engines that are approved by you all?

**Comment by wfleming** [comment]
You can run a custom engine locally: first, you would build your local engine image with a name like `codeclimate/codeclimate-markdownlint`, and add it to your project's `.codeclimate.yml` with config something like:

```yaml
engines:
  markdownlint:
    enabled: true
```

When you run the CLI, you have to supply the `--dev` flag (run `codeclimate analyze --dev`), so that the CLI will run engines aside from our approved engines.

Right now releasing an engine for our platform as a whole does require approval from us (those approved engines are what `engines:list` shows), but that's not at all necessary to get started building it & getting it working!

**Comment by devth** [comment]
Ok, awesome. Thanks for the info @wfleming. 

I'd definitely want to get it approved eventually as my goal would be to use it with a [new plugin](https://github.com/devth/yetibot-codeclimate) I released today for my chatbot, which would require being able to dynamically locate/download the docker image.

It'd be nice to know ahead of time whether 1) CodeClimate people think there's a need for it and 2) whether they would add it to approved engines once it meets the standards before embarking on dev of a custom engine. Markdown isn't the only thing I'm curious about contributing.

**Comment by pbrisbin** [comment]
> whether CodeClimate people think there's a need for it

FWIW, I'd enable a markdown linter on my own projects.

One of the big drivers behind the Platform and its openness is to allow easy creation and use of any niche engines folks are willing to build. Whether we choose to write and maintain an engine ourselves is one thing, but I don't see any reason we wouldn't want any and all engines the OSS community is willing to build.

> whether they would add it to approved engines once it meets the standards 

I can't think of any reason we wouldn't approve an engine if it met the standards. Otherwise, we should probably change the standards, right?

**Comment by wfleming** [comment]
One of our team members, @jpignata, ended up [making this engine](https://github.com/jpignata/codeclimate-markdownlint) recently as part of a hack week. So this engine now exists & is available for use on the CLI & http://codeclimate.com. We'll post a more detailed post on [our changelog](https://codeclimate.com/changelog) later this week, but for now, @devth, you should be able to start using this engine today. It's early days, so if you'd like to see opportunities for improvement & want to contribute, please take a look at [the engine's repo](https://github.com/jpignata/codeclimate-markdownlint). Thanks for the suggestion!

**Comment by devth** [comment]
Yesssssssssssss :space_invader: :100: :ocean:  Nice work @jpignata!

I'll start running it against all my repos.
