### ISSUE TITLE
safe_yaml

### ISSUE THREAD

**Issue by rafamanzo** [codeclimate/codeclimate#375]
The way `safe_yaml` is required modifies the global environment and leaves it modified for all the code running even after codeclimate's finished. This can break code not expecting for such behaviour.

I've tracked down `YAML` module usage to the following files:

* codeclimate/lib/cc/analyzer/config.rb
   * Uses default `YAML#safe_load` and do not require `safe_yaml`
* codeclimate/spec/cc/cli/init_spec.rb
  * Uses default `YAML#safe_load` and do not require `safe_yaml`
* codeclimate/lib/cc/analyzer/engine_registry.rb
  * Loads only a yaml file that can be trusted (as it is here in the source), so can safely use just `YAML#load_file`
*  codeclimate/spec/cc/cli/engines/list_spec.rb
 * Loads only a yaml file that can be trusted (as it is here in the source), so can safely use just `YAML#load_file`

So, can I suggest to just remove `safe_yaml` and use Ruby's default YAML (Psych) features? I'm up to open a PR modifying this if you agree on this.

Thanks!

**Comment by pbrisbin** [comment]
Hey @rafamanzo, thanks very much for bringing this to our attention. I'd be in favor of using `YAML#safe_load` everywhere (regardless of if we consider the source trusted or not) and then, once that's done, removing `safe_yaml`.

If you'd like to open that PR, that'd be great. Otherwise, we'll look to make this change when we're able to.
