### ISSUE TITLE
I'm trying to install codeclimate cli on Windows 10 to make it work with atom.

### ISSUE THREAD

**Issue by XaBerr** [codeclimate/codeclimate#402]
I'm trying to install codeclimate cli on Windows 10 to make it work with atom.
I followed the procedure:
- Install docker
- docker pull codeclimate/codeclimate<br>
#
I am not an experienced docker, so now what should I do to have a executable path to be given to atom?<br>
_Thanks in advance._

**Comment by wfleming** [comment]
Hi @XaBerr,

We think you might be our first Windows user for the CLI, so we don't have all the kinks worked out for setting it up and using it on Windows yet. That said, I just ran through a quick setup on a Windows machine, and I think it is doable, so I think we can figure it out together.

1. You'll need to setup [`docker` to run from the Windows Command Prompt](https://docs.docker.com/windows/step_one/#step-3-verify-your-installation), including creating a new Docker Machine VM, etc. if you haven't already done that.

    Note: I don't think `docker-machine` on Windows will automatically start the VM when you reboot your computer. You might want to see if you can configure your machine to do that: otherwise you'll need to manually start the VM using `docker-machine start` anytime you reboot your computer.

2. The following is a rough batch file I wrote that will run the Code Climate CLI from `cmd.exe`. Note that you have to replace `MACHINE_NAME` with whatever you actually named your docker machine VM in step 1. Please copy this into a file named `codeclimate.cmd` wherever you want to keep that file on your hard drive.

    ```bat
@ECHO OFF
SETLOCAL

FOR /f "tokens=*" %%i IN ('docker-machine env MACHINE_NAME') DO %%i

SET CODECLIMATE_CODE=%CD:\=/%
SET CODECLIMATE_CODE=%CODECLIMATE_CODE:C:=/c%
SET CODECLIMATE_TMP=%TEMP:\=/%/codeclimate
SET CODECLIMATE_TMP=%CODECLIMATE_TMP:C:=/c%

docker run ^
   --interactive --rm ^
   --env CODECLIMATE_CODE ^
   --env CODECLIMATE_TMP ^
   --env CODECLIMATE_DEBUG ^
   --volume "%CODECLIMATE_CODE%":/code ^
   --volume "%CODECLIMATE_TMP%":/tmp/cc ^
   --volume /var/run/docker.sock:/var/run/docker.sock ^
   codeclimate/codeclimate %*
    ```

    This script is a bit limited right now: it doesn't have any real error handling, and is limited to running against directories on the "C:\" drive. It should be enough to get started with, though.

3. You can test that everything's ok so far by opening a `cmd.exe` prompt, cd-ing to the directory where you saved `codeclimate.cmd`, and running it. It should print the CLI's help screen. (Note that it will probably pull the docker image again first: since this is using a docker machine VM, the image you already pulled is living on a different VM.)

    You can further confirm that the CLI script above is working by cd-ing to the source directory of your project in the shell, and typing `path\to\codeclimate.cmd engines:install` and `path\to\codeclimate.cmd analyze` to see analysis results directly before configuring the Atom integration.

4. At this point, you should be ready to configure Atom to use your `codeclimate.cmd` script: just set the `executablePath` for the plugin to the path to where your `codeclimate.cmd` script is saved.

Let me know if you run into trouble following the above steps or anything doesn't work. We'd love to get this hammered out so we can make this easier for other Windows users in the future!

**Comment by XaBerr** [comment]
Hi @wfleming,

Thank you for answering so fast.<br>
I'm stuck on the third point in your amazing guide.
I added the file in this path: `C:\codeclimate.cmd`
if I'll try cd-ing stuff like `codeclimate  help` everything work,
but when I try to enter this path in atom: 
`C:/codeclimate`
I get this error:

> codeclimate binary not found! Installation instructions at http://github.com/codeclimate/codeclimate

if I try this path instead:
`C:/codeclimate.cmd`
I get this error:

> Error: Impossibile trovare il percorso specificato.
> Error: Impossibile trovare il percorso specificato.
>     at exit (file:///C:/Users/user_12/.atom/packages/linter-codeclimate/node_modules/atom-linter/lib/helpers.coffee:32:24)
>     at triggerExitCallback (C:\Users\user_12\AppData\Local\atom\app-1.6.2\resources\app.asar\src\buffered-process.js:213:47)
>     at C:\Users\user_12\AppData\Local\atom\app-1.6.2\resources\app.asar\src\buffered-process.js:227:18
>     at Socket.<anonymous> (C:\Users\user_12\AppData\Local\atom\app-1.6.2\resources\app.asar\src\buffered-process.js:98:18)
>     at emitOne (events.js:82:20)
>     at Socket.emit (events.js:169:7)
>     at Pipe._onclose (net.js:469:12)

What have I forgotten?

**Comment by wfleming** [comment]
Silly question, but did you try `C:\codeclimate.cmd` (backslash instead of forward slash) in Atom?

I didn't actually go all the way through installing Atom & setting up the plugin on my Windows box when I put together those instructions. If it's not just the path needing the other kind of slash, let me know & I'll try to reproduce on my machine.

**Comment by XaBerr** [comment]
Same errors for `C:/codeclimate.cmd` `C:\codeclimate.cmd`!

**Comment by wfleming** [comment]
I dug into this more @XaBerr. Unfortunately, the `linter-codeclimate` Atom plugin currently assumes it's running in a Unix environment in several key ways, and we don't have an immediate fix for that. I'm sorry I wasn't aware of that limitation when we started this.

I've filed https://github.com/AtomLinter/linter-codeclimate/issues/25 with details of what I think needs to get addressed in that plugin for Windows support. I'm sorry I don't know  exactly when we'll be able to schedule that work.

Since you've gotten the CLI working, though, you can continue to use that directly until this is addressed. Hopefully that's still useful to you!

**Comment by pbrisbin** [comment]
> Since you've gotten the CLI working, though...

Hi @XaBerr it sounds like you've gotten the CLI itself working but are having some trouble with the atom plugin. Would you consider that resolved enough to close this Issue?

**Comment by XaBerr** [comment]
I'm sorry I have not tried in the hope of having the complete package.
I try between three days when I get back to work.

**Comment by XaBerr** [comment]
I've tried:
`analyze [-f format] [-e engine] <path>`
with this file in C:\
```
@ECHO OFF
SETLOCAL
SET MACHINE_NAME=%default%
FOR /f "tokens=*" %%i IN ('docker-machine env %MACHINE_NAME%') DO %%i
SET CODECLIMATE_CODE=%CD:\=/%
SET CODECLIMATE_CODE=%CODECLIMATE_CODE:C:=/c%
SET CODECLIMATE_TMP=%TEMP:\=/%/codeclimate
SET CODECLIMATE_TMP=%CODECLIMATE_TMP:C:=/c%

docker run ^
--interactive --rm ^
--env CODECLIMATE_CODE ^
--env CODECLIMATE_TMP ^
--env CODECLIMATE_DEBUG ^
--volume "%CODECLIMATE_CODE%":/code ^
--volume "%CODECLIMATE_TMP%":/tmp/cc ^
--volume /var/run/docker.sock:/var/run/docker.sock ^
codeclimate/codeclimate %*
```
and seems doesn't work
![immagine](https://cloud.githubusercontent.com/assets/16030020/15108416/12306df4-15d6-11e6-85e0-19082a9da0fd.png)

**Comment by wfleming** [comment]
Hi @XaBerr,

The CLI always analyzes the project in the current directory. File arguments can be given to specify which files in that directory to analyze, but in your case they'd have to be given as the relative Unix paths they are inside the Docker VM, not Windows paths. So just running `C:\codeclimate analyze` would try to analyze all of the files in `C:\wamp64\www\JUICE\projects\JATE`, but if you wanted to just analyze one file or directory you'd want to run `C:\codeclimate analyze dist` `C:\codeclimate analyze dist/some/file.js`.

Can you please set `CODECLIMATE_DEBUG` in your environment by running `Set CODECLIMATE_DEBUG=1` in the command window, and then run `C:\codeclimate analyze` and provide that output here if it's still failing? If you're still getting that same error message, please also check that your docker VM is mounting your Windows drive in the expected way: you can ssh into the Docker VM by running `docker-machine ssh default`, and then you should check that `ls /c/wamp64/www/JUICE/projects/JATE` shows the expected directory contents.

**Comment by XaBerr** [comment]
still getting that same error message
![immagine2](https://cloud.githubusercontent.com/assets/16030020/15138709/f1899e56-1691-11e6-8761-307485b01f16.png)

and seems docker VM isn't mounting my Windows drive in the expected way.

![immagine3](https://cloud.githubusercontent.com/assets/16030020/15138742/289287be-1692-11e6-854f-8dd99ce0a0e1.png)

**Comment by wfleming** [comment]
I don't think any of our team are familiar enough with the specifics of Docker on Windows to be much help on the file visibility issue there, sorry, @XaBerr. Since that looks like a docker-machine issue of, you might want to consider asking something on the [Docker Forum](https://forums.docker.com/) or Stack Overflow, or seeing if there are any relevant questions there under the [`docker` and `windows` tags](http://stackoverflow.com/questions/tagged/docker+windows).

**Comment by XaBerr** [comment]
I open new [topic](https://forums.docker.com/t/docker-vm-windows-10-mount-volume-issues/11854).
I'm waiting for news.

**Comment by XaBerr** [comment]
I have done some progress. Now I see the folder and try to send the command but I get the same error.
![immagine4](https://cloud.githubusercontent.com/assets/16030020/15286828/5bb7eb94-1b5f-11e6-9c86-a2450af3dbe3.png)

**Comment by wfleming** [comment]
Hi @XaBerr,

If you're going to run the CLI via `docker run`, then there are a number of other options needed: please refer to [the details in the README](https://github.com/codeclimate/codeclimate#usage).

Avoiding needing to remember and type all those options is why we provide [a wrapper script](https://github.com/codeclimate/codeclimate/blob/master/codeclimate-wrapper) for Unix platforms. It looks like you're now trying to run Code Climate from a terminal inside of your Docker Machine instead of from a Windows command line. You may want to copy that wrapper script into your Docker Machine if that's how you intend to run the CLI in the future.

**Comment by XaBerr** [comment]
> If you're going to run the CLI via docker run, then there are a number of other options needed

Crap...
Now it works correctly!
I'm the first user in windows 10 :)

**Comment by gerard2p** [comment]
Hello I'm trying run codeclimete on windows, It seem to be working, but when I run "codeclimate analyze" i get this:
```zsh
C:\development\koaton [v1 +26 ~41 -11 | +36 ~11 -51 !]> codeclimate analyze
[DEBUG] duplication:stable engine config: {"enabled":true,"config":{"languages":["javascript"]},"include_paths":["src/"]}
[DEBUG] docker run: ["docker", "run", "--name", "cc-engines-duplication-stable-b472b3a4-0ca1-465b-a9c4-163d61ee3ff4", "--cap-drop", "all", "--label", "com.codeclimate.label=825aa059-d90b-44be-ba10-576a945833b7", "--memory", "512000000", "--memory-swap", "-1", "--net", "n
one", "--rm", "--volume", "c:/development/koaton:/code:ro", "--volume", "c:/Users/gerar/AppData/Local/Temp/codeclimate/fe85c283-7c63-4639-a531-d8d5c9ebd622:/config.json:ro", "--user", "9000:9000", "codeclimate/codeclimate-duplication"]
error: (CC::Analyzer::Engine::EngineFailure) engine duplication:stable failed with status 2 and stderr
invalid value "c:/development/koaton:/code:ro" for flag --volume: bad format for volumes: c:/development/koaton:/code:ro
See 'docker run --help'.
[DEBUG] backtrace: /usr/src/app/lib/cc/analyzer/raising_container_listener.rb:23:in `finished'
        /usr/src/app/lib/cc/analyzer/composite_container_listener.rb:17:in `block in finished'
        /usr/src/app/lib/cc/analyzer/composite_container_listener.rb:17:in `each'
        /usr/src/app/lib/cc/analyzer/composite_container_listener.rb:17:in `finished'
        /usr/src/app/lib/cc/analyzer/container.rb:78:in `run'
        /usr/src/app/lib/cc/analyzer/engine.rb:52:in `run'
        /usr/src/app/lib/cc/analyzer/engines_runner.rb:60:in `block in run_engine'
        /usr/src/app/lib/cc/analyzer/formatters/plain_text_formatter.rb:60:in `with_spinner'
        /usr/src/app/lib/cc/analyzer/formatters/plain_text_formatter.rb:41:in `block in engine_running'
        /usr/src/app/lib/cc/analyzer/formatters/formatter.rb:29:in `engine_running'
        /usr/src/app/lib/cc/analyzer/formatters/plain_text_formatter.rb:40:in `engine_running'
        /usr/src/app/lib/cc/analyzer/engines_runner.rb:59:in `run_engine'
        /usr/src/app/lib/cc/analyzer/engines_runner.rb:23:in `block in run'
        /usr/src/app/lib/cc/analyzer/engines_runner.rb:23:in `each'
        /usr/src/app/lib/cc/analyzer/engines_runner.rb:23:in `run'
        /usr/src/app/lib/cc/cli/analyze.rb:20:in `block in run'
        /usr/src/app/lib/cc/cli/analyze.rb:18:in `chdir'
        /usr/src/app/lib/cc/cli/analyze.rb:18:in `run'
        /usr/src/app/lib/cc/cli/command.rb:24:in `execute'
        /usr/src/app/lib/cc/cli/runner.rb:22:in `run'
        /usr/src/app/lib/cc/cli/runner.rb:8:in `run'
        /usr/src/app/bin/codeclimate:6:in `<main>'
Starting analysis
C:\development\koaton [v1 +26 ~41 -11 | +36 ~11 -51 !]>
```
and my .codeclimate.yml is:
```yml
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
    paths:
    - "src/**"
exclude_paths:
- .nyc_output/
- docs/
- core/
- node_modules/
- lib/
- test/
- testcoverage/
- testingapp/
- templates/
- koaton
- .*
- ./**.json
- ./**.md
- ./*.js
```

the command spends a lot to give an output longest time was 240+ seconds

Hope you can help me.

**Comment by gerard2p** [comment]
I've actually find a way to do it, I've make a pull request and now I can even run it with the linter-codeclimate for atom puglin.

**Comment by XaBerr** [comment]
@gerard2p excellent!
