### ISSUE TITLE
«Definition for rule 'import/no-unresolved' was not found [eslint]»

### ISSUE THREAD

**Issue by nadeemja** [codeclimate/codeclimate#432]
Hi,

I think I've correctly configured `eslint-plugin-import` and my `.eslintrc.js`, but I'm stilling getting:

    Definition for rule 'import/no-unresolved' was not found [eslint]

Here's my .eslintrc.js:

    module.exports = {
      plugins: [
        'meteor',
        'import',
      ],
      extends: [
        'airbnb/base',
        'plugin:meteor/recommended',
        'plugin:import/errors',
        'plugin:import/warnings',
      ],
      env: {
        meteor: true,
        node: true,
        browser: true,
        jquery: true,
        es6: true,
      },
      rules: {
        'no-console': 0,
        'no-underscore-dangle': 0,
        'meteor/no-session': 0,
        'import/no-unresolved': [2, { ignore: ['^meteor/*'] }],
      },
    };

**Comment by wfleming** [comment]
Hi @nadeemja,

We unfortunately do not currently support arbitrary ESLint plugins: since plugins are effectively arbitrary remote code executing on our system, we need to be very careful about our architecture choices before we can support them. Right now we bundle & whitelist several plugins into the engine (`eslint-config-airbnb`, `eslint-plugin-react`, and `eslint-plugin-babel`), but other plugins won't work.

This is something we'd certainly like to support, but I'm sorry we're not there yet. We have several issues discussing this restriction on the [codclimate-eslint](https://github.com/codeclimate/codeclimate-eslint) repo right now, and that engine repo is a more appropriate place to discuss these changes, so I'm going to go ahead and close this issue. Please keep an eye out there for updates.

**Comment by rreckonerr** [comment]
Hi @wfleming! Do you still plan to add support for elsint plugins?

**Comment by efueger** [comment]
Hi @rreckonerr - Emily here, stepping in for Will.

We do support **eslint-plugin-import** on [our eslint-7 channel](https://github.com/codeclimate/codeclimate-eslint/blob/channel/eslint-7/package.json#L58) (in addition to channels 4, 5, and 6).

To use those version channels, [specify them in your .codeclimate.yml](https://docs.codeclimate.com/docs/eslint#eslint-versions), like this:
```
plugins: 
  eslint:
    enabled: true
    channel: "eslint-7"
``` 

- Are you looking for additional plugins? 
- Feel free to drop a line to help@codeclimate.com with your repo info and we'll take a closer look 👍

**Comment by rreckonerr** [comment]
@efueger I've switched to eslint-7, but still see error mentioned in this issue:

```yml
plugins:
  eslint:
    enabled: true
    channel: "eslint-7"
```

<img width="830" alt="image" src="https://user-images.githubusercontent.com/30495731/96841981-275b4280-1455-11eb-8ec8-377a02a46636.png">
