### ISSUE TITLE
Is there anyway to install codeclimate CLI without docker?

### ISSUE THREAD

**Issue by anoobbava** [codeclimate/codeclimate#469]
I am using ubuntu 14.04 LTS machine for ROR development. When I tried to install docker for the codeclimate CLI which is shown that necessary for codeclimate it shows the "Docker currently only supports 64bit platforms." is there any way; using omit the docker and use codeclimate CLI

**Comment by pbrisbin** [comment]
Hi @anoobbava unfortunately the CLI does require Docker.

Since Engines often have to be written in the language they analyze, a version of our CLI that didn't rely on the them being containerized would require the user have a working environment for a prohibitively large set of programming languages and frameworks. You'd need to have various versions of interpreters installed, any dependencies they use, and if the engine were a compiled language, we would need to do a lot of cross-compiling and your architecture would have to be one we supported.

I'm really sorry about the limitation, but the CLI would likely be impossible for us to build and maintain otherwise. Maybe you'd find value in using our hosted analysis instead/only?

**Comment by pbrisbin** [comment]
I'm going to go ahead and close this issue now. I hope my explanation was valuable.

**Comment by anoobbava** [comment]
"Maybe you'd find value in using our hosted analysis instead/only?" is it means?

**Comment by pbrisbin** [comment]
I meant that, even though you can't use the CLI for local analysis, you could still add your project(s) on codeclimate.com and see the results of analysis there.

**Comment by frakman1** [comment]
@anoobbava 

I am running 32 bit Ubuntu 14.04 and was able to install docker.

```bash
$cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"

$uname -a
Linux kubuntu14 4.4.0-59-generic #80~14.04.1-Ubuntu SMP Fri Jan 6 18:02:23 UTC 2017 i686 i686 i686 GNU/Linux

$docker --version
Docker version 1.6.2, build 7c8fca2

#proof it really is 32-bit:
$file `which ls`
/bin/ls: ELF 32-bit LSB  executable, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=cecbb9e27978d91bc6fe2cc4d46d0cd58deafdb2, stripped

```

**Comment by rraallvv** [comment]
How about having the CLI uploading the source files to analyze them and the pull the results to show them in the console, the whole point for me would be to have a way to know the analysis results before committing and pushing to the repository. Installing docker is something that I'd do only as a last resource.
