### ISSUE TITLE
Permission denied @ dir_chdir - /code (Errno::EACCES)

### ISSUE THREAD

**Issue by acarpe** [codeclimate/codeclimate#54]
Installed via homebrew on osx 10.10.4.
Updated to version `0.0.22` via brew upgrade, re-ran `codeclimate engines:install`
Inside the project directory running `codeclimate analyze` I continue to get

```
Starting analysis
Running rubocop: Done!
error: (CC::Analyzer::Engine::EngineFailure) engine rubocop failed with status 1 and stderr
"/usr/src/app/lib/cc/engine/rubocop.rb:16:in `chdir': Permission denied @ dir_chdir - /code (Errno::EACCES)\n\t
from /usr/src/app/lib/cc/engine/rubocop.rb:16:in `run'\n\t
from /usr/src/app/bin/codeclimate-rubocop:12:in `<main>'\n"
```

**Comment by pbrisbin** [comment]
What are the permissions on the current directory when you run `codeclimate analyze`? You should be able to see that with `stat .` or `ls -l ../`.

**Comment by acarpe** [comment]
Access: (0700/drwx------)  Uid: (  503/    silk)   Gid: (   20/   staff)

**Comment by pbrisbin** [comment]
So that is the issue. You've only given read access to the user bit. The group and (most importantly) all cannot read this directory.

```
7 - user (503/silk) can read (+4) / write (+2) / execute (+1)
0 - group (20/staff) can do nothing
0 - all can do nothing
```

*Note*: for directories "execute" means "able to change into the directory and/or list directory contents".

These are unusual permissions for a project directory and prevents anyone other than the user (503/silk) from entering the directory or seeing anything within it. This is also preventing our CLI from reading the code for the purposes of analysis (it does not run as you, it runs as a dedicated, unprivileged user).

I'd recommend opening up the permissions on this directory with `chmod 755 .`

```
7 - user can read/write/execute
5 - group can read/execute
5 - all can read/execute
```

If this gets you passed your current error but you find more permissions errors on files or directories *within* the project, it's possible they also have unexpectedly restrictive permissions on them as well. In that case you can either exclude them using `exclude_paths` or modify their permissions similarly.

**Comment by acarpe** [comment]
changed permission (why not adding a check on permission before starting? ) and it has gone forward.
Now the issue seems to be about the `exclude_paths` not being considered:
`Error: EACCES, permission denied '/code/vendor/assets/javascripts/fastclick.js`

it started from the stuff in the public folder and in fact all files had wrong permission but adding:
```
exclude_paths:
- public
- public/**/*
- public/*
```
didn't work, at the end I updated all permissions inside public folder but it started the same behaviour in the vendor folder :(

**Comment by pbrisbin** [comment]
Does

```yaml
exclude_paths
- public/**
- vendor/**
```

Not work?

**Comment by pbrisbin** [comment]
> why not adding a check on permission before starting?

Unfortunately we have to prioritize improvements like this against all the other things we want to do and we just haven't gotten to it yet. Please know that it's on our roadmap though.

**Comment by pbrisbin** [comment]
@acarpe i believe your issue is the same as #82, which we've hopefully just released a fix for. I'm going to close this and centralize discussion there.

Sorry for the troubles and the long time to fix, it was a much more complicated issue than it appeared.

**Comment by lucasmartins** [comment]
I've had the same problem, *disabling SElinux* "solves" it.
