### ISSUE TITLE
How can i use my own plugin or extend in stylelint engine?

### ISSUE THREAD

**Issue by konstantin24121** [codeclimate/codeclimate#633]
In my stylelintrc.js 
```
module.exports = {
  "extends": [
    "stylelint-config-standard",
    "stylelint-config-css-modules",
  ],
  "plugins": [
    "stylelint-performance-animation",
  ],
...
```
In codeclimat.yaml i turn on stylelint engine and take this error on codeclimete

•• Timing: .engineConfig: 0.049s
Error: Could not find "stylelint-config-css-modules". Do you need a `configBasedir`?
See our documentation at https://docs.codeclimate.com/docs/stylelint for more information.

Can somebody explain me how enable plugins ands extends if it posible?

**Comment by ABaldwinHunter** [comment]
Hi @konstantin24121!

Thanks for writing in. Today, a Code Climate engine won't make network calls to install arbitrary third party plugins during analysis. See https://github.com/codeclimate/codeclimate/issues/480 for an explanation of why.

However, there's a workaround. Many engines come packaged with relevant plugins already installed. You can go ahead and open an issue or PR on the [stylelint project](https://github.com/gilbarbara/codeclimate-stylelint/blob/master/package.json#L25)  to add the dependency you'd like to use. 

For an example, our ESLint engine supports a [variety of plugins](https://github.com/codeclimate/codeclimate-eslint/blob/master/package.json) that has grown in number over time. Here's an [example of a PR](https://github.com/codeclimate/codeclimate-eslint/pull/264/files) updating the list.

I'm going to go ahead and close the issue here, since we have the general network access issue above, and the Stylelint engine repo is probably a better place to address adding this specific dependency.
