### ISSUE TITLE
DockerHub page has incorrect information

### ISSUE THREAD

**Issue by matthewwiesen** [codeclimate/codeclimate#710]
On DockerHub (https://hub.docker.com/r/codeclimate/codeclimate/), it shows the install anywhere command as;

```
curl -L https://github.com/codeclimate/codeclimate/archive/v0.0.6.tar.gz | tar xvz
cd codeclimate-* && sudo make install
```

This information on this page is outdated and should match what is listed in the README here as `master.tar.gz`

**Comment by dblandin** [comment]
@mattaningram Thanks for the heads up! Looks like the description on DockerHub and the README here have drifted considerably.

I just updated the description with the current content in the README. We might also want to look into linking the DockerHub repo so that it tracks README changes automatically in the future.

Thanks!
