### ISSUE TITLE
Codeclimate docker-in-docker security flaw

### ISSUE THREAD

**Issue by narutozak** [codeclimate/codeclimate#722]
Hi,

Thank you very much for your contributions with such a great project.

I'd like to bring to discussion what I see as a security flaw, in the current approach which is taken and used by CC.

It's possible and I will welcome corrections/comments - perhaps I have it all wrong.

The only way to run CodeClimate is inside a docker container, and the docker socket is mounted inside for CC to be able to `docker pull` the relevant engines.

When this is integrated, with - for example - GitLab - the [recommended](https://docs.gitlab.com/ee/ci/examples/code_climate.html) (and only) way is for a `.gitlab.yml` file to have a `codeclimate` entry which sets up the docker container to analyze the source from the repository - and in this way it's integrated by GL in the Merge Request views, etc.

But this file where the `codeclimate` entry is defined is actually controlled by the user who creates a Merge Request - so the same user, could add a docker command that will create and run a new container that takes over the host OS - e.g. injecting a new root user, a new autostart script after reboot, etc. - they can become root on the host system.  After this has been achieved - many things can happen, including snooping on all the source code arriving from other projects to `codequality` and even worse.

If the above is true - then, using CC in the recommended way (at least with GL) - introduces a security risk - where developer who creates an MR can take over the host, and use it to later gain access to project they might not have access to.

Please, let me know what are your comments on the above scenario - is there any recommended way to run securely with GitLab? (without docker-in-docker, or at least without privileged mode?)

I hope there is and I missed it :)

**Comment by ale7714** [comment]
Hi @narutozak,

Thank you for reaching out. We take security concerns seriously.

Our CLI needs to pull images and run containers to perform analysis; that's why 
it needs access to the Docker daemon.  The containers created by the CLI to run 
engines have restricted permissions, with no access to the Docker daemon 
socket. You can read more about engines specification [here](https://github.com/codeclimate/spec/blob/master/SPEC.md#resource-restrictions).

When running CC on a CI provider, similar to running other tools (e.g. rspec), 
it is important to configure your CI build in a secure way. Most CI providers 
will have mechanisms in-place to prevent certain malicious actions and to 
prevent a user from gaining control of shared resources. Most often, this means 
running your CI builds inside their own VM or container. I don't know the 
specifics for GitLab but it would also be a good idea to check in with them.

Let us know if you have any other questions or concerns, and thank you for your 
interest in Code Climate.

**Comment by narutozak** [comment]
Hi @ale7714,

Thanks for response.

I agree - this problem should indeed be secure by the CI - and opened [a security issue in GitLab](https://gitlab.com/gitlab-org/gitlab-ce/issues/37980) for this matter.   For now it looks like they concur there's a problem, but no solution for the time being.

Thank you - you may close the issue if there's nothing further to be done on CC side.
