### ISSUE TITLE
"codeclimate init" unknown command init

### ISSUE THREAD

**Issue by Miouge1** [codeclimate/codeclimate#781]
Version 0.70.0 removed the "codeclimate init" as a valid command, this break retro compatibility.

this non-retro compatible change is not explicit in the [release note](https://github.com/codeclimate/codeclimate/releases/tag/v0.70.0).

**Comment by aequitas** [comment]
Not codeclimate's fault, but using init is still suggested in Gitlab CI docs: https://docs.gitlab.com/ee/ci/examples/code_climate.html

**Comment by patvdleer** [comment]
Does this mean `init` should simply be removed from the run/`gitlab-ci.yml` ?

**Comment by aequitas** [comment]
@patvdleer I dunno, I cargoculted it and try currently running without it but so far no luck[0]. I also tried switching to the previous release but it resulted in the same error[1].

The issue next to this one https://github.com/codeclimate/codeclimate/issues/782 seems to point towards a solution i'm going to try now.

[0] https://gitlab.com/failmap/admin/-/jobs/40773069
[1] https://gitlab.com/failmap/admin/-/jobs/40777317

**Comment by aequitas** [comment]
Job completed without failure: https://gitlab.com/failmap/admin/-/jobs/40782684

Did not compare results yet, my assumption is `init` generates linter configuration files which are used during the `analyze` command. Maybe this might cause discrepancies.

**Comment by wfleming** [comment]
My apologies @Miouge1, I listed this in the [pull request introducing the changes](https://github.com/codeclimate/codeclimate/pull/777), but accidentally omitted that copy from the [release notes](https://github.com/codeclimate/codeclimate/releases/tag/v0.70.0). I've copied that information over to the release notes now. Thanks for filing this.

> my assumption is init generates linter configuration files which are used during the analyze command. Maybe this might cause discrepancies.

@aequitas that is correct, and is what `init` used to do. We've removed that functionality as part of wider changes to our analysis to [provide better out-of-the-box feedback on code quality](http://blog.codeclimate.com/blog/2017/09/21/a-new-clearer-way-to-understand-code-quality/). Please note we're *not* removing support for linters like RuboCop, ESLint, etc., but we're no longer enabling them by default or providing our own opinionated default configurations for those tools. An up to date list of the plugins we support and how  to configure them is available in our [documentation](https://docs.codeclimate.com/).

We have adjusted what `init` enabled by default in the past, so relying on `init` could also have resulted in discrepancies before now. For users with their own preferences about what plugins to use, we always recommend committing the relevant linter configuration files and a `.codeclimate.yml` controlling what plugins you want to run.

For all gitlab CI users, yes, we recommend removing usage of `codeclimate init`. Please note [a bug affecting the JSON formatter of the CLI](https://github.com/codeclimate/codeclimate/issues/782) was also caught this morning, which will also affect GitLab usage. We're sorry that bug slipped into the release & should have a bugfix release out shortly.

I'm going to go ahead and close this issue since it was filed for our failure to sufficiently document the `init` removal, which I think I've addressed.

**Comment by gitlab-winnie** [comment]
@wfleming Thank you for the detailed explanation! 👍 

We are tracking the GitLab documentation update in https://gitlab.com/gitlab-org/gitlab-ce/issues/40276.

**Comment by aequitas** [comment]
@wfleming thanks for the swift response and resolution.
