### ISSUE TITLE
Can the codeclimate to color output for CLI ?

### ISSUE THREAD

**Issue by 2ur1st** [codeclimate/codeclimate#836]
I found this [post](https://codeclimate.com/changelog/55a68fd3e30ba03215003107/) about disabled colorized output data, but **may be stay ability to colorized output**  ?

**Comment by ale7714** [comment]
@2ur1st 👋 Ale from Code Climate. Thank you for writing. We don't have any immediate plans to add support back for colorized output. But we welcome contributions from the community. You (or someone else) could open a PR that adds a flag so the CLI outputs colorized output optionally. Thanks again!

**Comment by wfleming** [comment]
To clarify here, the CLI does still colorize output. It only removes colors if it detects that the output is not going to a tty that supports colors, which is generally what happens when you're piping or redirecting output (e.g. `codeclimate analyze | grep` or `codeclimate analyze > results.txt`). The change is [described here](https://github.com/codeclimate/codeclimate/pull/363).

What situation are you in where you're piping or redirecting but still want the escape sequences? That usually just leads to seeing escape characters in output like `\033[0;31mhello world\033[0m`.

If there's an interest in making this possible, I'd suggest opening a PR to change the `codeclimate-wrapper` shell script to support an environment variable to force running with `--tty`.

**Comment by wfleming** [comment]
I think the question has been addressed, and it doesn't seem like any action is needed or planned right now, so I'm going to close this.

**Comment by asdkant** [comment]
I'm trying to work on a PR to enable this feature (I want color in my GitLab CI pipeline), but I'm using the `codeclimate/codeclimate` docker image directly so the solution is not completely in the `codeclimate-wrapper` script, I need to do something in whatever runs as an entrypoint for the image.

Can someone give me some guidance on where's the logic that (a) detects whether the code is running inside a TTY or not and (b) disables color if it's not the case?
