### ISSUE TITLE
CodeClimate CLI full (absolute) file path?

### ISSUE THREAD

**Issue by KevinVerre** [codeclimate/codeclimate#845]
I want to run codeclimate CLI on a particular file.

This worked:
codeclimate analyze ./appname/filename.rb

This did NOT work:
codeclimate analyze /Users/myname/code/appname/filename.rb

Instead it tried to run codeclimate on the entirety of ./appname . Which is not what I want since that would take a really long time.

Is anyone else experiencing this? Should I try to fix it?

**Comment by wilson** [comment]
The CLI only volume-mounts (in the `docker -v` sense) the current working directory, unless you explicitly set the `CODECLIMATE_CODE` environment variable.

In this case, the file exists under the working directory, but is not accessible via the full path, which is different inside the container.

What we should probably do here instead is normalize the input files based on their shared prefixes.

So if you did: `codeclimate analyze /foo/baz/qux /foo/bar/baz.rb`
..we would `docker -v /foo:/code` and pass the relative paths `baz/qux` and `bar/baz.rb` to the analysis plugin.

I'll try to fit that into our future planning, though a patch that implemented such behavior would be very welcome.

**Comment by wfleming** [comment]
I'm going to close this, as I think supporting absolute paths is an anti-feature that will only make things more confusing. The fact that the CLI and all the analysis it performs is fundamentally connected to how docker works would make supporting this quite tricky. If an absolute file path could be specified, there are some awkward cases that would arise.

Analysis always occurs within the context of a repo, since the repo is what provides configuration, both for the Code Climate CLI and for any plugins being used (e.g. RuboCop). If an absolute path were used for analysis, then either:

1. That absolute path needs to point to a path underneath the current working directory (which we consider to be the root of the repo used to determine configuration context), in which case supporting an absolute path is not very helpful and would lead to other confusing usages since the absolute path would be required to be relative to the current working directory. Or:
2. If the absolute path really could be arbitrarily anywhere, then the CLI either needs to determine where the repo root is within that path hierarchy, or it would still use the current working directory (which would greatly complicate code since there would need to be separate volume mounts for config and analysis), or it would have to be settable via a flag (which comes with the same code complications). That's a degree of complication we'd find undesirable.
