### ISSUE TITLE
Client tool not performing checks section

### ISSUE THREAD

**Issue by medaamarnadh** [codeclimate/codeclimate#894]
Hi there!

Sorry you're having trouble with our CLI, and thanks for taking the time to
report the issue to us.

There are a few reasons _not_ to open an issue here. Please consider the
following:

- Is this an issue with your Docker installation in general?

NO

- Are you invoking `docker run codeclimate/codeclimate` without other options?

    Yes

- Are you having trouble using this project as a gem or not via Docker?
No

## Guidelines

If you'd still like to report this issue, please follow these guidelines:

- Make sure your problem exists in the latest version of the CLI and any engines
  you're using, the following commands will update everything:

  ```
  docker pull codeclimate/codeclimate
  codeclimate engines:install
  ```

- Include the exact command you're running and its complete output

  ```
  CODECLIMATE_DEBUG=1 codeclimate analyze -e:eslint -f html
  ```
The main problem is codeclimate not analyzing the checks such as maximum lines for method, maximum for lines for file etc.

  Include the output of the following commands:

Can you please resolve this issue ?

**Comment by wfleming** [comment]
Sorry for the delayed response here. This issue is old enough that I kind of doubt you still need assistance here one way or the other, but:

> The main problem is codeclimate not analyzing the checks such as maximum lines for method, maximum for lines for file etc.

Are you referring to checks from ESLint for those issues, or Code Climate's provided [Maintainability](https://docs.codeclimate.com/docs/maintainability) checks?

If you're referring to the checks from ESLint, it'd be helpful to see your ESLint config file here.

If you're referring to Code Climate's own checks, I think it's because the command you're running has the `-e` flag to specify running only `eslint`. The CLI runs all configured engines by default: the `-e/--engine` flags are for running *just* specific selected engines/plugins. So with `-e eslint` specified, Code Climate's own checks are not running.

**Comment by wfleming** [comment]
Closing due to age and inactivity. I realize that's largely on us for not responding faster, so I apologize for that. Ff this is still an issue, please comment here after I've closed it and I'll get back to you.
